// 주요 한국 도시 데이터 (Programmatic SEO용)
export interface CityData {
  slug: string;
  name: string;
  nameEn: string;
  lat: number;
  lon: number;
  description: string;
}

export const CITIES: CityData[] = [
  {
    slug: "seoul",
    name: "서울",
    nameEn: "Seoul",
    lat: 37.5665,
    lon: 126.978,
    description: "대한민국 수도",
  },
  {
    slug: "busan",
    name: "부산",
    nameEn: "Busan",
    lat: 35.1796,
    lon: 129.0756,
    description: "대한민국 제2의 도시, 해양 도시",
  },
  {
    slug: "incheon",
    name: "인천",
    nameEn: "Incheon",
    lat: 37.4563,
    lon: 126.7052,
    description: "서해안 항구 도시",
  },
  {
    slug: "daegu",
    name: "대구",
    nameEn: "Daegu",
    lat: 35.8714,
    lon: 128.6014,
    description: "영남 내륙 중심 도시",
  },
  {
    slug: "daejeon",
    name: "대전",
    nameEn: "Daejeon",
    lat: 36.3504,
    lon: 127.3845,
    description: "충청권 중심 도시, 과학의 도시",
  },
  {
    slug: "gwangju",
    name: "광주",
    nameEn: "Gwangju",
    lat: 35.1595,
    lon: 126.8526,
    description: "호남권 중심 도시, 예술의 도시",
  },
  {
    slug: "suwon",
    name: "수원",
    nameEn: "Suwon",
    lat: 37.2636,
    lon: 127.0286,
    description: "경기도청 소재지, 화성 행궁의 도시",
  },
  {
    slug: "ulsan",
    name: "울산",
    nameEn: "Ulsan",
    lat: 35.5384,
    lon: 129.3114,
    description: "산업 수도, 동해안 도시",
  },
  {
    slug: "changwon",
    name: "창원",
    nameEn: "Changwon",
    lat: 35.2281,
    lon: 128.6811,
    description: "경남도청 소재지",
  },
  {
    slug: "seongnam",
    name: "성남",
    nameEn: "Seongnam",
    lat: 37.4449,
    lon: 127.1389,
    description: "분당 신도시, IT 허브",
  },
  {
    slug: "bundang",
    name: "분당",
    nameEn: "Bundang",
    lat: 37.3825,
    lon: 127.1195,
    description: "성남시 분당구, 1기 신도시",
  },
  {
    slug: "pangyo",
    name: "판교",
    nameEn: "Pangyo",
    lat: 37.3947,
    lon: 127.1112,
    description: "판교테크노밸리, IT 스타트업 허브",
  },
  {
    slug: "goyang",
    name: "고양",
    nameEn: "Goyang",
    lat: 37.6584,
    lon: 126.832,
    description: "일산 신도시, 킨텍스",
  },
  {
    slug: "ilsan",
    name: "일산",
    nameEn: "Ilsan",
    lat: 37.6686,
    lon: 126.7695,
    description: "고양시 일산, 호수공원",
  },
  {
    slug: "yongin",
    name: "용인",
    nameEn: "Yongin",
    lat: 37.2411,
    lon: 127.1775,
    description: "에버랜드, 수지/기흥",
  },
  {
    slug: "gwacheon",
    name: "과천",
    nameEn: "Gwacheon",
    lat: 37.4339,
    lon: 126.9876,
    description: "과천시, 서울대공원/과천과학관",
  },
  {
    slug: "bucheon",
    name: "부천",
    nameEn: "Bucheon",
    lat: 37.5034,
    lon: 126.766,
    description: "문화예술의 도시, 만화/영화의 도시",
  },
  {
    slug: "anyang",
    name: "안양",
    nameEn: "Anyang",
    lat: 37.3943,
    lon: 126.9568,
    description: "평촌 신도시, 예술공원",
  },
  {
    slug: "ansan",
    name: "안산",
    nameEn: "Ansan",
    lat: 37.3219,
    lon: 126.8309,
    description: "시화호, 다문화 도시",
  },
  {
    slug: "hwaseong",
    name: "화성",
    nameEn: "Hwaseong",
    lat: 37.1996,
    lon: 126.8312,
    description: "동탄 신도시, 삼성 캠퍼스",
  },
  {
    slug: "dongtan",
    name: "동탄",
    nameEn: "Dongtan",
    lat: 37.2003,
    lon: 127.0745,
    description: "화성시 동탄, 2기 신도시",
  },
  {
    slug: "pyeongtaek",
    name: "평택",
    nameEn: "Pyeongtaek",
    lat: 36.9921,
    lon: 127.0857,
    description: "삼성전자/미군기지, 고덕신도시",
  },
  {
    slug: "gwangmyeong",
    name: "광명",
    nameEn: "Gwangmyeong",
    lat: 37.4786,
    lon: 126.8644,
    description: "KTX광명역, 광명동굴",
  },
  {
    slug: "uijeongbu",
    name: "의정부",
    nameEn: "Uijeongbu",
    lat: 37.7381,
    lon: 127.0337,
    description: "경기 북부 중심 도시",
  },
  {
    slug: "namyangju",
    name: "남양주",
    nameEn: "Namyangju",
    lat: 37.636,
    lon: 127.2166,
    description: "다산신도시, 북한강/남한강",
  },
  {
    slug: "paju",
    name: "파주",
    nameEn: "Paju",
    lat: 37.7126,
    lon: 126.7612,
    description: "출판단지, 운정신도시",
  },
  {
    slug: "gimpo",
    name: "김포",
    nameEn: "Gimpo",
    lat: 37.6153,
    lon: 126.7156,
    description: "김포공항, 한강신도시",
  },
  {
    slug: "hanam",
    name: "하남",
    nameEn: "Hanam",
    lat: 37.5393,
    lon: 127.2147,
    description: "스타필드, 미사강변도시",
  },
  {
    slug: "guri",
    name: "구리",
    nameEn: "Guri",
    lat: 37.5943,
    lon: 127.1295,
    description: "왕숙천, 동구릉",
  },
  {
    slug: "siheung",
    name: "시흥",
    nameEn: "Siheung",
    lat: 37.38,
    lon: 126.8028,
    description: "시화MTV, 월곶",
  },
  {
    slug: "cheongju",
    name: "청주",
    nameEn: "Cheongju",
    lat: 36.6424,
    lon: 127.489,
    description: "충북도청 소재지",
  },
  {
    slug: "jeonju",
    name: "전주",
    nameEn: "Jeonju",
    lat: 35.8242,
    lon: 127.148,
    description: "전북도청 소재지, 한옥마을",
  },
  {
    slug: "jeju",
    name: "제주",
    nameEn: "Jeju",
    lat: 33.4996,
    lon: 126.5312,
    description: "대한민국 최대 관광지, 섬",
  },
];

// slug로 도시 찾기
export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES.find((city) => city.slug === slug);
}

// 모든 slug 목록
export function getAllCitySlugs(): string[] {
  return CITIES.map((city) => city.slug);
}
